#!/bin/bash

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Configure nginx
sudo sh -c "echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        server_name _;

        location / {
                return 200 \"Hello World!\";
        }
}' > /etc/nginx/sites-available/default"

# Restart nginx
sudo /etc/init.d/nginx restart

