#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend samson-frontend
        bind *:80
        mode http
        default_backend samson-backend

backend samson-backend
        balance roundrobin
        server 122481-web-01 54.160.100.61:80 check
        server 122481-web-02 100.25.152.160:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
